create table tb_role (id bigint not null auto_increment, role_authority varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_solicitacao (id bigint not null auto_increment, data date, json_pedido longtext, primary key (id)) engine=InnoDB;
create table tb_user (id binary(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_users_roles (user_id binary(255) not null, role_id bigint not null) engine=InnoDB;
alter table tb_role add constraint UK_7pi4fc21o4y6655j8e3udsmal unique (role_authority);
alter table tb_user add constraint UK_4wv83hfajry5tdoamn8wsqa6x unique (username);
alter table tb_users_roles add constraint FK6p4o2kxbq23rthm174k19xo2h foreign key (role_id) references tb_role (id);
alter table tb_users_roles add constraint FK85qorv8qojsxvl1nv56vckxmj foreign key (user_id) references tb_user (id);
create table tb_role (id bigint not null auto_increment, role_authority varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_solicitacao (id bigint not null auto_increment, date date, json_pedido longtext, primary key (id)) engine=InnoDB;
create table tb_user (id binary(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_users_roles (user_id binary(255) not null, role_id bigint not null) engine=InnoDB;
alter table tb_role add constraint UK_7pi4fc21o4y6655j8e3udsmal unique (role_authority);
alter table tb_user add constraint UK_4wv83hfajry5tdoamn8wsqa6x unique (username);
alter table tb_users_roles add constraint FK6p4o2kxbq23rthm174k19xo2h foreign key (role_id) references tb_role (id);
alter table tb_users_roles add constraint FK85qorv8qojsxvl1nv56vckxmj foreign key (user_id) references tb_user (id);
create table tb_role (id bigint not null auto_increment, role_authority varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_solicitacao (id bigint not null auto_increment, data date not null, json_pedido longtext, primary key (id)) engine=InnoDB;
create table tb_user (id binary(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_users_roles (user_id binary(255) not null, role_id bigint not null) engine=InnoDB;
alter table tb_role add constraint UK_7pi4fc21o4y6655j8e3udsmal unique (role_authority);
alter table tb_solicitacao add constraint UK_bu47mncybttqc1xh03ywhrvdg unique (data);
alter table tb_user add constraint UK_4wv83hfajry5tdoamn8wsqa6x unique (username);
alter table tb_users_roles add constraint FK6p4o2kxbq23rthm174k19xo2h foreign key (role_id) references tb_role (id);
alter table tb_users_roles add constraint FK85qorv8qojsxvl1nv56vckxmj foreign key (user_id) references tb_user (id);
create table tb_role (id bigint not null auto_increment, role_authority varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_solicitacao (id bigint not null auto_increment, date date not null, json_pedido longtext, primary key (id)) engine=InnoDB;
create table tb_user (id binary(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_users_roles (user_id binary(255) not null, role_id bigint not null) engine=InnoDB;
alter table tb_role add constraint UK_7pi4fc21o4y6655j8e3udsmal unique (role_authority);
alter table tb_solicitacao add constraint UK_2ho56vxsnhcqr4ehpagv92h6j unique (date);
alter table tb_user add constraint UK_4wv83hfajry5tdoamn8wsqa6x unique (username);
alter table tb_users_roles add constraint FK6p4o2kxbq23rthm174k19xo2h foreign key (role_id) references tb_role (id);
alter table tb_users_roles add constraint FK85qorv8qojsxvl1nv56vckxmj foreign key (user_id) references tb_user (id);
create table tb_role (id bigint not null auto_increment, role_authority varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_solicitacao (id bigint not null auto_increment, data date not null, json_pedido longtext, primary key (id)) engine=InnoDB;
create table tb_user (id binary(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_users_roles (user_id binary(255) not null, role_id bigint not null) engine=InnoDB;
alter table tb_role add constraint UK_7pi4fc21o4y6655j8e3udsmal unique (role_authority);
alter table tb_solicitacao add constraint UK_bu47mncybttqc1xh03ywhrvdg unique (data);
alter table tb_user add constraint UK_4wv83hfajry5tdoamn8wsqa6x unique (username);
alter table tb_users_roles add constraint FK6p4o2kxbq23rthm174k19xo2h foreign key (role_id) references tb_role (id);
alter table tb_users_roles add constraint FK85qorv8qojsxvl1nv56vckxmj foreign key (user_id) references tb_user (id);
create table tb_role (id bigint not null auto_increment, role_authority varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_solicitacao (id bigint not null auto_increment, data date not null, json_pedido longtext, primary key (id)) engine=InnoDB;
create table tb_user (id binary(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_users_roles (user_id binary(255) not null, role_id bigint not null) engine=InnoDB;
alter table tb_role add constraint UK_7pi4fc21o4y6655j8e3udsmal unique (role_authority);
alter table tb_solicitacao add constraint UK_bu47mncybttqc1xh03ywhrvdg unique (data);
alter table tb_user add constraint UK_4wv83hfajry5tdoamn8wsqa6x unique (username);
alter table tb_users_roles add constraint FK6p4o2kxbq23rthm174k19xo2h foreign key (role_id) references tb_role (id);
alter table tb_users_roles add constraint FK85qorv8qojsxvl1nv56vckxmj foreign key (user_id) references tb_user (id);
create table tb_role (id bigint not null auto_increment, role_authority varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_solicitacao (id bigint not null auto_increment, data date not null, json_pedido longtext, primary key (id)) engine=InnoDB;
create table tb_user (id binary(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_users_roles (user_id binary(255) not null, role_id bigint not null) engine=InnoDB;
alter table tb_role add constraint UK_7pi4fc21o4y6655j8e3udsmal unique (role_authority);
alter table tb_solicitacao add constraint UK_bu47mncybttqc1xh03ywhrvdg unique (data);
alter table tb_user add constraint UK_4wv83hfajry5tdoamn8wsqa6x unique (username);
alter table tb_users_roles add constraint FK6p4o2kxbq23rthm174k19xo2h foreign key (role_id) references tb_role (id);
alter table tb_users_roles add constraint FK85qorv8qojsxvl1nv56vckxmj foreign key (user_id) references tb_user (id);
create table tb_role (id bigint not null auto_increment, role_authority varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_solicitacao (id bigint not null auto_increment, date date, json_pedido longtext, primary key (id)) engine=InnoDB;
create table tb_user (id binary(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_users_roles (user_id binary(255) not null, role_id bigint not null) engine=InnoDB;
alter table tb_role add constraint UK_7pi4fc21o4y6655j8e3udsmal unique (role_authority);
alter table tb_user add constraint UK_4wv83hfajry5tdoamn8wsqa6x unique (username);
alter table tb_users_roles add constraint FK6p4o2kxbq23rthm174k19xo2h foreign key (role_id) references tb_role (id);
alter table tb_users_roles add constraint FK85qorv8qojsxvl1nv56vckxmj foreign key (user_id) references tb_user (id);
create table tb_role (id bigint not null auto_increment, role_authority varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_solicitacao (id bigint not null auto_increment, date date, json_pedido longtext, primary key (id)) engine=InnoDB;
create table tb_user (id binary(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_users_roles (user_id binary(255) not null, role_id bigint not null) engine=InnoDB;
alter table tb_role add constraint UK_7pi4fc21o4y6655j8e3udsmal unique (role_authority);
alter table tb_user add constraint UK_4wv83hfajry5tdoamn8wsqa6x unique (username);
alter table tb_users_roles add constraint FK6p4o2kxbq23rthm174k19xo2h foreign key (role_id) references tb_role (id);
alter table tb_users_roles add constraint FK85qorv8qojsxvl1nv56vckxmj foreign key (user_id) references tb_user (id);
create table tb_role (id bigint not null auto_increment, role_authority varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_solicitacao (id bigint not null auto_increment, data date not null, json_pedido longtext, primary key (id)) engine=InnoDB;
create table tb_user (id binary(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_users_roles (user_id binary(255) not null, role_id bigint not null) engine=InnoDB;
alter table tb_role add constraint UK_7pi4fc21o4y6655j8e3udsmal unique (role_authority);
alter table tb_solicitacao add constraint UK_bu47mncybttqc1xh03ywhrvdg unique (data);
alter table tb_user add constraint UK_4wv83hfajry5tdoamn8wsqa6x unique (username);
alter table tb_users_roles add constraint FK6p4o2kxbq23rthm174k19xo2h foreign key (role_id) references tb_role (id);
alter table tb_users_roles add constraint FK85qorv8qojsxvl1nv56vckxmj foreign key (user_id) references tb_user (id);
