create table tb_solicitacao (id int8 generated by default as identity, json_pedido varchar(255), primary key (id));
create table tb_solicitacao (id int8 generated by default as identity, json_pedido oid, primary key (id));
create table tb_solicitacao (id int8 generated by default as identity, json_pedido oid, primary key (id));
create table tb_solicitacao (id int8 generated by default as identity, json_pedido text, primary key (id));
create table tb_solicitacao (id int8 generated by default as identity, json_pedido text, primary key (id));
